### ISSUE TITLE
Rate Control

### ISSUE THREAD

**Issue by jennerfer** [aws-samples/aws-control-tower-controls-terraform#2]
How is it managed to ensure that only 10 resources are created at the same time? In CloudFormation, we have to use the 'DependOn' attribute to achieve a similar result.

**Comment by igirardi** [comment]
@jennerfer thank you for your question. When performing CRUD operations on resources AWS Terraform Provider handles the retry in the background for you. Some information is the [Terraform documentation](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts). For AWS Control Tower controls I think the default timeout is set to 60 minutes for create and delete operations (please check the source code in the repository https://github.com/hashicorp/terraform-provider-aws (from a recent commit I can see timeouts of 60 minutes [here](https://github.com/hashicorp/terraform-provider-aws/blob/be60d1a695cb3bb6079d34d05e90a9b9b02d10f7/internal/service/controltower/control.go#L39-L41)). Please let me know if you need additional information and if I can close this issue.
